management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  application:
    name: Spring Internet-provider Application
    description: Spring application for provision of Internet provider services.
    version: 1.0.0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/internet_provider_spring
    username: root
    password: vorona2017V
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true