management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  application:
    name: Spring Internet-provider Application
    description: Spring application for provision of Internet provider services.
    version: 1.0.0